% MATLAB Editor Run Commands
% @version 3
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name vdp26
%  @associatedFile /Users/adamtameer/Documents/MATLAB/vdp26.m
%  @mostRecentlyActioned true
%  @uniqueId 134ecfaf:1797774bf5b:-7fdb

vdp26(t, y)

